# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-03 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201203_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 1, 14, 78069), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 1, 14, 79070), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='text',
            field=models.TextField(default='Заказ123', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 1, 14, 78069), verbose_name='Дата'),
        ),
    ]
