# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-03 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201203_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 22, 9, 132653), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 22, 9, 133653), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='text',
            field=models.CharField(default='Заказ123', max_length=20, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 13, 22, 9, 133653), verbose_name='Дата'),
        ),
    ]
