# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_auto_20201204_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='status',
            field=models.TextField(default='В обработке', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 4, 8, 53, 57, 690261), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 4, 8, 53, 57, 691262), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 4, 8, 53, 57, 690261), verbose_name='Дата'),
        ),
    ]
