# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-20 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20201204_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 20, 23, 44, 17, 626876), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 20, 23, 44, 17, 626876), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.TextField(default='В очереди', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 20, 23, 44, 17, 626876), verbose_name='Дата'),
        ),
    ]
